name: CI/CD Pipeline para GeoLocator

on:
  push:
    branches: [ "main" ]

jobs:
  # Job que roda em paralelo
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Simula verificação de estilo de código
        run: echo "Este job simula uma verificação de estilo e roda em paralelo com os testes."

  # Job para executar os testes
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Executar testes com Maven
        run: mvn test

      - name: Upload do relatório de testes como artefato
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: target/surefire-reports/

  # Job para empacotar a aplicação (Build)
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Empacotar com Maven
        run: mvn clean package

      - name: Upload do pacote JAR como artefato
        uses: actions/upload-artifact@v4
        with:
          name: pacote-aplicacao
          path: target/*.jar

  # Job para enviar a notificação
  notify:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Enviar notificação por e-mail
        uses: dawidd6/action-send-mail@v3 # <-- Usa uma Action pronta
        with:
          # Configuração abrangente via variáveis
          server_address: ${{ vars.SMTP_SERVER_ADDRESS }}
          server_port: ${{ vars.SMTP_SERVER_PORT }}

          # Credenciais seguras do repositório
          username: ${{ secrets.SENDER_EMAIL }}
          password: ${{ secrets.SENDER_PASSWORD }}

          # Assunto e corpo do e-mail
          subject: "Notificação de Pipeline - ${{ github.repository }}"
          body: "Pipeline para o repositório ${{ github.repository }} foi executado com sucesso! Veja a execução em: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Destinatário
          to: ${{ vars.RECIPIENT_EMAIL }}

          # Remetente
          from: GitHub Actions <${{ secrets.SENDER_EMAIL }}>